# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

#Build Environments
os: linux
dist: xenial

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Define o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test

# Definir o Deploy no Heroku
# Definir o Deploy no Google AppEngine
deploy:
  provider: heroku
  strategy: api
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devopslab-antoniomerlini
  on:
        branch: main

  provider: gae
    keyfile: ../lab-devops-cloud-aagmerlini-11a71eb4791d.json 
    project: lab-devops-cloud-aagmerlini
    on:
      branch: main
  before_install:
  - openssl aes-256-cbc -K $encrypted_abcc27d58914_key -iv $encrypted_abcc27d58914_iv
    -in lab-devops-cloud-aagmerlini-11a71eb4791d.json.enc -out ../lab-devops-cloud-aagmerlini-11a71eb4791d.json
    -d

